# Generated by Django 4.0.3 on 2022-03-18 18:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id_user', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('birthdate', models.CharField(max_length=10)),
                ('passworord', models.CharField(max_length=30)),
            ],
        ),
    ]
