# Generated by Django 4.0.3 on 2022-03-18 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='passworord',
            new_name='password',
        ),
    ]
