# Generated by Django 4.0.3 on 2022-03-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_passworord_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='y7eNQ3AULXb6eHTMrPXk6ChgV4MN3J', max_length=30),
        ),
    ]
