# Generated by Django 4.0.3 on 2022-03-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(blank=True, default='TWSZz55NpkFp7Qa2HSDAD7ZGPsLAnd', max_length=30, null=True),
        ),
    ]
