# Generated by Django 4.0.3 on 2022-03-19 18:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_users_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('birthdate', models.CharField(max_length=10)),
                ('password', models.CharField(default='v5MKjwEDkhLNAD43SwML6NDhEMdjcY', max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
