# Generated by Django 4.0.3 on 2022-03-19 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_birthdate_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='xhYMWy7CK7jJK6JDtwKcJAwh6RpPap', max_length=30),
        ),
    ]
